### ISSUE TITLE
item difficulty estimation

### ISSUE THREAD

**Issue by eloiup** [douglasrizzo/catsim#5]
Hi,

I 've just started studing about IRT (using IRT by Frank Baker and SeockHo Kim), and the catsim library (thx it looks like great work)

While this might be in the documentation (havent found it yet), does catsim support estimation for the item difficult parameter theta?

My problem at hand is: I have a bunch of questions/candidates and interactions without any further knowledge (questions on same topic) and need to properly estimate the question difficulty as well as the candidates proficiency.

Any examples/documentation referrals wld be deeply appreciated. Thx again.

**Comment by douglasrizzo** [comment]
Hi @eloiup. Currently, catsim does not support item parameter estimation. It only estimates examinees proficiencies while simulating/applying a computerized adaptive test.

In order to estimate item parameters, I'd recommend the R language and its packages [mirt](https://cran.r-project.org/web/packages/mirt/index.html) and [irtoys](https://cran.r-project.org/web/packages/irtoys/index.html).

The closest I found to IRT parameter estimation in Python is Khan Academy's [guacamole](https://github.com/Khan/guacamole) repository, but I've never used it.

If you'd like to know more about catsim, check out this [paper](https://arxiv.org/abs/1707.03012).

**Comment by vivekpalakkat** [comment]
Can you please guide me how to apply a computerized adaptive test?
I have item parameters , administered items, response vector and est_theta for each candidate.

While using "estimator.estimate" funciton,
what should i pass for parameter "index", can i ignore this parameter as im finding new estimate after the candidate answer each question?

How,when should i use the simulator?
